AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Welcome to Aegis Combat Systems. This Cloudformation template will set up various security parameters on your account.
Parameters:
  Email:
      Type: String
      Description: Please enter your email for the Simple Notification Service
      Default: email
Resources:
  AegisCombatSystem:
      Type: AWS::Events::Rule
      Properties:
        Description: "user detection system"
        EventPattern:
          detail-type:
            - "AWS Console Sign In via CloudTrail"
        State: "ENABLED"
        Targets:
          -
            Arn:
              Ref: "AegisInstanceSystems"
            Id: "OpsTopic"
            InputTransformer:
              InputPathsMap:
                MFA: "$.detail.additionalEventData.MFAUsed"
                action: "$.detail.eventName"
                arn: "$.detail.userIdentity.arn"
                loginrate: "$.detail.responseElements.ConsoleLogin"
                mobile: "$.detail.additionalEventData.MobileVersion"
                region: "$.detail.awsRegion"
                sector: "$.detail.additionalEventData.LoginTo"
                sourceip: "$.detail.sourceIPAddress"
                time: "$.detail.eventTime"
                user: "$.detail.userIdentity.userName"
                userAgent: "$.detail.userAgent"
              InputTemplate: |
                "Aegis Secure Combat Systems has detected an sign in event."
                "User: <user> has attempted the API call: <action>"
                "Source IP: <sourceip>"
                "User Agent Detected: <userAgent>"
                "ARN: <arn>"
                "Region: <region>"
                "Time(UTC): <time>"
                "MFA status <MFA>"
                "Mobile Version: <mobile>"
                "Sector: <sector>"
                "Status: <loginrate>."
  AegisInstanceSystems:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email
